cart/urls.py
from django.urls import path
from . import views 

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

coupon/urls.py
from django.urls import path
from . import views

app_name='coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

orders/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _

app_name = 'orders'

urlpatterns = [
    path(_('create/'), views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf')
]

procentapi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _


urlpatterns = i18n_patterns(
    path(_("admin/"), admin.site.urls),
    path(_("cart/"), include("cart.urls", namespace="cart")),
    path(_("orders/"), include("orders.urls", namespace="orders")),
    path(_("payment/"), include("payment.urls", namespace="payment")),
    path(_("coupons/"), include("coupon.urls", namespace="coupons")),
    path("rosetta/", include("rosetta.urls")),
    path("users/", include("users.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("shop.urls", namespace="shop")),
    # path('api-auth/', include('rest_framework.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views 

app_name= 'shop'

urlpatterns = [
    path('', views.shop, name='home'),
    path('product_list/', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name="product_detail"),
]

cart/models.py
from django.db import models

cart/forms.py
from django import forms 
from django.utils.translation import gettext_lazy as _

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices = PRODUCT_QUANTITY_CHOICES,
        coerce=int,
        label=_('Quantity')
    )
    override = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse

from shop.models import Product
from shop.recommender import Recommender
from coupon.forms import CouponApplyForm
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product= product,
            quantity=cd['quantity'],
            override_quantity=cd['override']
        )
    return redirect('cart:cart_detail')


#  Todo: Add ajax to this function to fix 302 error
@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')
    # return JsonResponse({'redirect_url': reverse('cart:cart_detail')})

def cart_detail(request):
    cart = Cart(request)
    # allow users to update the quantity of the products on the cart
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={
                'quantity': item['quantity'],
                'override': True
            }
        )
    coupon_apply_form = CouponApplyForm()
    r = Recommender()
    cart_products = [item['product'] for item in cart]
    # recommended_products = r.suggest_products_for(cart_products, max_results=4)
    recommended_products = Product.objects.order_by('-created')[:4]
    return render(request, 'cart/detail.html', {'cart': cart,
                                                'coupon_apply_form': coupon_apply_form,
                                                'recommended_products':recommended_products
                                                })

cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %} Your cart{% endblock title %}
{% block content %}
<h1> Your shopping cart</h1>
<table class="cart">
    <thead class="thead-dark">
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart  %}
        {% with product=item.product %}
        <tr>
            <td>
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{product.image.url}} 
                    {% else %} {% static 'img/no_image.png' %}{% endif %}">
            </td>
            <td>{{product.name}}</td>
            <td>
                <form action="{% url 'cart:cart_add' product.id %} "method="post">
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.override }}
                    {% csrf_token %}
                    <input type="submit" value="Update"> 
                </form>
            </td>
            <td>
                <form id="removeForm" action="{% url 'cart:cart_remove' product.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Remove">
                </form>

                <script>
                    function removeFromCart() {
                        const form = document.getElementById('removeForm');
                        const formData = new FormData(form);
                        fetch(form.action, {
                            method: 'POST',
                            body: formData,
                            headers: {
                                'X-CSRFToken': '{{ csrf_token }}'
                            }
                        })
                        .then(response => {
                            if (response.ok) {
                                console.log("item removed successfully")
                                return response.json()
                            } else {
                                console.log("handling error for failed removal")
                                throw new Error('Network response was not ok')
                            }
                        })
                        .then( data=> {
                            if (data.redirect.url) {
                                window.location.href = data.redirect_url;
                            } else {
                                // handle other response if needed
                            }
                        })
                        .catch(error => {
                            console.error('Error:', error)
                        })
                    }
                </script>
            </td>
            <td class="num">${{item.price}}</td>
            <td class="num">${{ item.total_price }}</td>
        </tr>
        {% endwith %}
        {% endfor %}
        {% if cart.coupon %}
            <tr class="subtotal">
                <td>Subtotal</td>
                <td colspan="4"></td>
                <td class="num">${{ cart.get_total_price|floatformat:2 }}</td>
            </tr> 
            <tr>
                <td>"{{ cart.coupon.code }}" coupon({{ cart.coupon.discount }}% off)</td>
                <td colspan="4"></td>
                <td class="num neg"> - ${{ cart.get_discount|floatformat:2 }}</td>
            </tr>
        {% endif %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price_after_discount|floatformat:2 }}</td>
        </tr>
    </tbody>
</table>
    {% if recommended_products %}
        <div class="recommendations cart">
            <h3>People who bought this also bought</h3>
            {% for p in recommended_products  %}
            <div class="item">
                <a href="{{ p.get_absolute_url}}">
                    <img src="{% if p.image %} {{ p.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                </a>
                <p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
            </div>
            {% endfor %}
        </div>
    {% endif %}
    <p>Apply a coupon:</p>
    <form action="{% url "coupons:apply" %}" method="post">
        {{ coupon_apply_form }}
        <input type="submit" value="Apply">
        {% csrf_token %}
    </form>
<p class="text-right">
    <a href="{% url 'shop:product_list' %}" class="button-light">Continue shopping </a>
    <a href="{% url 'orders:order_create' %}" class="button">Checkout </a>
</p>
{% endblock content %}
{% block scripts %}
    
{% endblock scripts %}